/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join */
        post: operations["join_api_agents__agent_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workstreams/{ws_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim */
        post: operations["claim_api_workstreams__ws_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workstreams/{ws_id}/declare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Declare */
        post: operations["declare_api_workstreams__ws_id__declare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workstreams/{ws_id}/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reassign Scope */
        post: operations["reassign_scope_api_workstreams__ws_id__scope_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workstreams/{ws_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submit_api_workstreams__ws_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Replace the local workspace with the seeded fixture.
         */
        post: operations["reset_api_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent */
        get: operations["recent_api_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objectives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Objective */
        post: operations["create_objective_api_objectives_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objectives/{objective_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_objectives__objective_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objectives/{objective_id}/orchestrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Orchestrate */
        post: operations["orchestrate_api_objectives__objective_id__orchestrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_agents__agent_id__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intentions/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Intention */
        post: operations["validate_intention_api_intentions_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conflicts/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect Conflicts */
        post: operations["detect_conflicts_api_conflicts_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conflicts/{conflict_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Conflict */
        post: operations["resolve_conflict_api_conflicts__conflict_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conflicts/{conflict_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Conflict */
        post: operations["approve_conflict_api_conflicts__conflict_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_api_agents__agent_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changesets/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Changeset */
        post: operations["submit_changeset_api_changesets_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objectives/{objective_id}/converge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Converge */
        post: operations["converge_api_objectives__objective_id__converge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_live_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Runs */
        get: operations["recent_runs_api_live_runs_get"];
        put?: never;
        /** Start */
        post: operations["start_api_live_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_live_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/runs/{run_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_live_runs__run_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_live_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_api_demo_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/acme-challenge/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Respond */
        get: operations["respond__well_known_acme_challenge__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service Descriptor
         * @description Self-description at the endpoint URL ANS registration seals.
         *
         *     Registration declares https://<host>/api as the agent endpoint. Sealing a
         *     URL that 404s would publish a claim the service does not honour, so this
         *     answers there and points at the agent card for the rest.
         */
        get: operations["service_descriptor_api_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/agent-card.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Card */
        get: operations["agent_card__well_known_agent_card_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentPrincipal */
        AgentPrincipal: {
            /** Id */
            id: string;
            /** Ans Name */
            ans_name: string;
            /** Role */
            role: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** Ans Agent Id */
            ans_agent_id?: string | null;
            /** Identity Cert Fingerprint */
            identity_cert_fingerprint?: string | null;
            /** Ans Status */
            ans_status?: string | null;
        };
        /** ApiContract */
        ApiContract: {
            /**
             * Method
             * @enum {string}
             */
            method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
            /** Path */
            path: string;
            /**
             * Role
             * @enum {string}
             */
            role: "provides" | "consumes";
            /** Request Fields */
            request_fields?: {
                [key: string]: string;
            };
            /** Response Fields */
            response_fields?: {
                [key: string]: string;
            };
        };
        /** ChangeSet */
        ChangeSet: {
            /** Id */
            id: string;
            /** Workstream Id */
            workstream_id: string;
            /** Agent Id */
            agent_id: string;
            /** Commit Sha */
            commit_sha?: string | null;
            /** Files */
            files: string[];
            contract: components["schemas"]["ApiContract"];
            /** Tests */
            tests?: components["schemas"]["TestResult"][];
        };
        /** ClaimRequest */
        ClaimRequest: {
            /** Agent Id */
            agent_id: string;
        };
        /** Conflict */
        Conflict: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "file" | "contract";
            /** Workstream Ids */
            workstream_ids: string[];
            /** Explanation */
            explanation: string;
            /** Conflicting Field */
            conflicting_field: string;
            /** Decision Id */
            decision_id?: string | null;
            /** Recommendation */
            recommendation: string;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "resolved";
        };
        /** Decision */
        Decision: {
            /** Decision Id */
            decision_id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Affected Component */
            affected_component: string;
            /** Created At */
            created_at: string;
        };
        /** DeclareRequest */
        DeclareRequest: {
            /** Agent Id */
            agent_id: string;
            contract: components["schemas"]["ApiContract"];
        };
        /** DemoAgent */
        DemoAgent: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Allowed Paths */
            allowed_paths: string[];
            /** Ans Name */
            ans_name?: string | null;
        };
        /** DemoRunResponse */
        DemoRunResponse: {
            /** Status */
            status: string;
            /** Agents */
            agents: string[];
            /** Detail */
            detail?: string | null;
        };
        /** Event */
        Event: {
            /** Event Id */
            event_id: string;
            /** Objective Id */
            objective_id: string;
            /** Workstream Id */
            workstream_id?: string | null;
            /** Agent Id */
            agent_id?: string | null;
            /** Event Type */
            event_type: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Timestamp */
            timestamp: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Identity Mode */
            identity_mode: string;
            /** Memory Mode */
            memory_mode: string;
            /**
             * Trace Mode
             * @default cache
             */
            trace_mode: string;
            /**
             * Live Integrations
             * @default false
             */
            live_integrations: boolean;
            /**
             * Identity Tier
             * @default none
             * @enum {string}
             */
            identity_tier: "badge" | "scitt" | "none";
            /**
             * Dpop Required
             * @default false
             */
            dpop_required: boolean;
        };
        /** IntentionContract */
        IntentionContract: {
            /** Name */
            name: string;
            /** Request Fields */
            request_fields?: string[];
            /** Response Fields */
            response_fields?: string[];
        };
        /** IntentionDocument */
        IntentionDocument: {
            /** Agent Id */
            agent_id: string;
            /** Objective Id */
            objective_id: string;
            /** Workstream Id */
            workstream_id: string;
            /** Summary */
            summary: string;
            /** Planned Files */
            planned_files?: string[];
            /** Planned Symbols */
            planned_symbols?: string[];
            /** Contracts Provided */
            contracts_provided?: components["schemas"]["IntentionContract"][];
            /** Contracts Consumed */
            contracts_consumed?: components["schemas"]["IntentionContract"][];
            /** Database Changes */
            database_changes?: string[];
            /** Dependencies */
            dependencies?: string[];
            /** Assumptions */
            assumptions?: string[];
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "low" | "medium" | "high";
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** LiveRunResponse */
        LiveRunResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
        };
        /** LiveStartRequest */
        LiveStartRequest: {
            /** Objective */
            objective: string;
        };
        /** Objective */
        Objective: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Acceptance Criteria */
            acceptance_criteria: string[];
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "complete";
        };
        /** ObjectiveRequest */
        ObjectiveRequest: {
            /**
             * Id
             * @default objective-oauth
             */
            id: string;
            /**
             * Title
             * @default Add organization-level OAuth login
             */
            title: string;
            /**
             * Description
             * @default Coordinate three agents before overlapping changes are written.
             */
            description: string;
            /** Acceptance Criteria */
            acceptance_criteria?: string[];
        };
        /** OrchestrationChangeSet */
        OrchestrationChangeSet: {
            /** Workstream Id */
            workstream_id: string;
            /** Agent Id */
            agent_id: string;
            /** Intention Version */
            intention_version: number;
            /** Branch */
            branch: string;
            /** Commit Sha */
            commit_sha?: string | null;
            /** Changed Files */
            changed_files: string[];
            /** Changed Symbols */
            changed_symbols?: string[];
            /** Contracts Provided */
            contracts_provided?: components["schemas"]["IntentionContract"][];
            /** Contracts Consumed */
            contracts_consumed?: components["schemas"]["IntentionContract"][];
            /** Database Changes */
            database_changes?: string[];
            tests: components["schemas"]["TestSummary"];
        };
        /** OrchestrationConflict */
        OrchestrationConflict: {
            /** Conflict Id */
            conflict_id: string;
            /** Objective Id */
            objective_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "FILE_CONFLICT" | "SYMBOL_CONFLICT" | "CONTRACT_CONFLICT" | "DEPENDENCY_CONFLICT" | "PERMISSION_CONFLICT" | "INTENT_DRIFT";
            /**
             * Severity
             * @enum {string}
             */
            severity: "LOW" | "MEDIUM" | "HIGH";
            /** Workstream Ids */
            workstream_ids: string[];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Related Decision Id */
            related_decision_id?: string | null;
            /**
             * Status
             * @default OPEN
             * @enum {string}
             */
            status: "OPEN" | "RESOLUTION_PROPOSED" | "AWAITING_APPROVAL" | "RESOLVED" | "REJECTED";
            /** Recommended Action */
            recommended_action?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Resolution */
            resolution?: {
                [key: string]: unknown;
            } | null;
        };
        /** OrchestrationEvent */
        OrchestrationEvent: {
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Timestamp */
            timestamp: string;
            /** Agent Id */
            agent_id?: string | null;
            /** Workstream Id */
            workstream_id?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** OrchestrationState */
        OrchestrationState: {
            objective?: components["schemas"]["Objective"] | null;
            /** Agents */
            agents?: components["schemas"]["DemoAgent"][];
            /** Workstreams */
            workstreams?: components["schemas"]["OrchestrationWorkstream"][];
            /** Conflicts */
            conflicts?: components["schemas"]["OrchestrationConflict"][];
            /** Events */
            events?: components["schemas"]["OrchestrationEvent"][];
        };
        /** OrchestrationWorkstream */
        OrchestrationWorkstream: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id: string;
            /** Title */
            title: string;
            /** Allowed Paths */
            allowed_paths: string[];
            /**
             * State
             * @default PENDING
             * @enum {string}
             */
            state: "PENDING" | "PLANNING" | "INTENT_SUBMITTED" | "VALIDATING" | "BLOCKED" | "APPROVED" | "EXECUTING" | "CHANGESET_SUBMITTED" | "CONVERGING" | "COMPLETE" | "FAILED";
            intention?: components["schemas"]["IntentionDocument"] | null;
            changeset?: components["schemas"]["OrchestrationChangeSet"] | null;
            /** Block Reason */
            block_reason?: string | null;
        };
        /** ResolutionApproval */
        ResolutionApproval: {
            /** Approved By */
            approved_by: string;
        };
        /** ResolutionProposal */
        ResolutionProposal: {
            /**
             * Recommended Action
             * @enum {string}
             */
            recommended_action: "UPDATE_CONTRACT" | "REASSIGN_FILE_OWNER" | "ADD_DEPENDENCY" | "SERIALIZE_WORKSTREAMS" | "SPLIT_SHARED_WORK" | "REQUEST_SCOPE_EXPANSION" | "REQUEST_HUMAN_REVIEW";
            /** Affected Workstreams */
            affected_workstreams: string[];
            /** Reasoning */
            reasoning: string;
            /** Proposed Changes */
            proposed_changes?: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence: number;
            /**
             * Requires Human Approval
             * @default false
             */
            requires_human_approval: boolean;
        };
        /** ScopeRequest */
        ScopeRequest: {
            /** Agent Id */
            agent_id: string;
            /** Owned Paths */
            owned_paths: string[];
        };
        /** TestResult */
        TestResult: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "not_run";
            /**
             * Source
             * @default agent_reported
             * @enum {string}
             */
            source: "agent_reported" | "synapse_executed";
        };
        /** TestSummary */
        TestSummary: {
            /** Passed */
            passed: number;
            /** Failed */
            failed: number;
        };
        /**
         * TraceEvent
         * @description Durable debugging record for coordinator and live-agent activity.
         */
        TraceEvent: {
            /** Trace Id */
            trace_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "coordinator" | "live_agent";
            /** Event Type */
            event_type: string;
            /** Timestamp */
            timestamp: string;
            /** Run Id */
            run_id?: string | null;
            /** Objective Id */
            objective_id?: string | null;
            /** Workstream Id */
            workstream_id?: string | null;
            /** Agent Id */
            agent_id?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceState */
        WorkspaceState: {
            /**
             * Phase
             * @default foundation
             * @constant
             */
            phase: "foundation";
            objective?: components["schemas"]["Objective"] | null;
            /** Workstreams */
            workstreams?: components["schemas"]["Workstream"][];
            /** Agents */
            agents?: components["schemas"]["AgentPrincipal"][];
            /** Conflicts */
            conflicts?: components["schemas"]["Conflict"][];
            /** Decisions */
            decisions?: components["schemas"]["Decision"][];
            /** Events */
            events?: components["schemas"]["Event"][];
        };
        /** Workstream */
        Workstream: {
            /** Id */
            id: string;
            /** Objective Id */
            objective_id: string;
            /** Title */
            title: string;
            /** Agent Id */
            agent_id: string;
            /** Owned Paths */
            owned_paths: string[];
            /** Depends On */
            depends_on?: string[];
            contract: components["schemas"]["ApiContract"];
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "active" | "blocked" | "complete";
            latest_changeset?: components["schemas"]["ChangeSet"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
        };
    };
    join_api_agents__agent_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_api_workstreams__ws_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    declare_api_workstreams__ws_id__declare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reassign_scope_api_workstreams__ws_id__scope_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_workstreams__ws_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ws_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceState"];
                };
            };
        };
    };
    recent_api_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_objective_api_objectives_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ObjectiveRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_objectives__objective_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objective_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orchestrate_api_objectives__objective_id__orchestrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objective_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_agents__agent_id__plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IntentionDocument"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_intention_api_intentions_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentionDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_conflicts_api_conflicts_detect_post: {
        parameters: {
            query: {
                objective_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_conflict_api_conflicts__conflict_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conflict_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_conflict_api_conflicts__conflict_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conflict_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolutionApproval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_api_agents__agent_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_changeset_api_changesets_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrchestrationChangeSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    converge_api_objectives__objective_id__converge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objective_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestrationState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_api_live_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    recent_runs_api_live_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    start_api_live_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_live_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_live_runs__run_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_live_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_demo_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoRunResponse"];
                };
            };
        };
    };
    respond__well_known_acme_challenge__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    service_descriptor_api_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    agent_card__well_known_agent_card_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
